[package]
name = "usp-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Rubens Andrade"]
license = "MIT"
description = "Create theses and dissertations at the University of São Paulo (USP) and the Institute of Mathematics and Statistics (IME)."
repository = "https://github.com/andrader/usp-thesis-typst-template"
keywords = [
    "academic",
    "thesis",
    "dissertation",
    "brazil",
    "usp",
    "imeusp",
    "University of São Paulo",
    "Institute of Mathematics and Statistics",
    "Universidade de São Paulo",
    "Instituto de Matemática e Estatística",
]
categories = ["thesis", "paper"]
disciplines = ["mathematics", "computer-science", "engineering"]
compiler = "0.12.0"

[template]
path = "src/template"
entrypoint = "main.typ"
